services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: developer_project_app
    volumes:
      - .:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"